/**
 * topology.ts — SimuFlow Shared Type Contract
 *
 * This file is the single source of truth for all data structures that cross
 * the frontend ↔ backend ↔ Web Worker boundary.
 *
 * Rules:
 *  1. Never import from React, MobX, or any UI library in this file.
 *  2. The backend Pydantic models in app/models/ must mirror every field here.
 *  3. Increment TOPOLOGY_VERSION on any breaking change to NodeDef or EdgeDef.
 *  4. Add new node types to NodeType enum only — never use raw strings elsewhere.
 */

// ─────────────────────────────────────────────────────────────────────────────
// VERSIONING
// ─────────────────────────────────────────────────────────────────────────────

export const TOPOLOGY_VERSION = "1.0" as const;

// ─────────────────────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────────────────────

export enum NodeType {
  Client       = "client",
  LoadBalancer = "load_balancer",
  ApiServer    = "api_server",
  Cache        = "cache",
  Database     = "database",
  Queue        = "queue",
  CDN          = "cdn",
  Microservice = "microservice",
}

export enum LBStrategy {
  RoundRobin      = "round_robin",
  LeastConnections = "least_connections",
  Random          = "random",
}

export enum NodeHealth {
  Idle       = "idle",      // simulation not running
  Healthy    = "healthy",   // utilisation < 60%
  Stressed   = "stressed",  // utilisation 60–90%
  Bottleneck = "bottleneck",// utilisation > 90%
  Failed     = "failed",    // failure rate triggered or chaos killed node
}

export enum ChaosScenarioId {
  DbFailover     = "DB_FAILOVER",
  CacheStampede  = "CACHE_STAMPEDE",
  NetPartition   = "NET_PARTITION",
  TrafficSpike   = "TRAFFIC_SPIKE",
  Cascade        = "CASCADE",
  SlowDependency = "SLOW_DEP",
}

export enum SimulationStatus {
  Idle    = "idle",
  Running = "running",
  Paused  = "paused",
  Chaos   = "chaos",  // running with at least one active chaos scenario
}

// ─────────────────────────────────────────────────────────────────────────────
// NODE CONFIG
// Each NodeType has its own config interface. NodeConfig is the discriminated
// union — use the `type` field to narrow to the correct config shape.
// ─────────────────────────────────────────────────────────────────────────────

export interface BaseNodeConfig {
  /** Max requests per second before node saturates. */
  capacity: number;
  /** Processing latency p50 in milliseconds. */
  latencyMs: number;
  /** Probability 0–1 that a given request fails at this node. */
  failureRate: number;
  /** Request timeout in ms. Requests exceeding this emit an error event. */
  timeoutMs: number;
}

export interface ClientConfig {
  /** Outbound requests per second generated by this source node. */
  rps: number;
  /** Whether this client generates burst traffic patterns. */
  burst: boolean;
}

export interface LoadBalancerConfig extends BaseNodeConfig {
  strategy: LBStrategy;
  /** Number of replicas of downstream nodes to distribute across. */
  replicas: number;
}

export interface CacheConfig extends BaseNodeConfig {
  /** Cache hit rate 0–1. On miss, request falls through to backing store. */
  hitRate: number;
}

export interface CDNConfig extends BaseNodeConfig {
  hitRate: number;
}

export interface QueueConfig {
  /** Processing delay added per message in milliseconds. */
  delayMs: number;
  /** Max queue depth before messages are dropped. 0 = unlimited. */
  maxDepth: number;
}

// Discriminated union — type field narrows which config fields are present
export type NodeConfig =
  | { nodeType: NodeType.Client;       config: ClientConfig }
  | { nodeType: NodeType.LoadBalancer; config: LoadBalancerConfig }
  | { nodeType: NodeType.ApiServer;    config: BaseNodeConfig }
  | { nodeType: NodeType.Cache;        config: CacheConfig }
  | { nodeType: NodeType.Database;     config: BaseNodeConfig }
  | { nodeType: NodeType.Queue;        config: QueueConfig }
  | { nodeType: NodeType.CDN;          config: CDNConfig }
  | { nodeType: NodeType.Microservice; config: BaseNodeConfig };

// ─────────────────────────────────────────────────────────────────────────────
// TOPOLOGY — the diagram data model saved to Supabase and loaded into the canvas
// ─────────────────────────────────────────────────────────────────────────────

export interface CanvasPosition {
  x: number;
  y: number;
}

export interface CanvasViewport {
  x: number;
  y: number;
  zoom: number;
}

/**
 * A single node on the canvas.
 * The `config` field is typed via the NodeConfig discriminated union —
 * narrow using `node.nodeType` before accessing `node.config`.
 */
export type SimNode = {
  id: string;           // nanoid — unique within diagram
  label: string;        // user-set display name
  position: CanvasPosition;
} & NodeConfig;

export interface SimEdge {
  id: string;           // nanoid — unique within diagram
  sourceId: string;     // ID of the source SimNode
  targetId: string;     // ID of the target SimNode
  /** Optional label shown on edge at idle — e.g. "SQL queries" */
  label?: string;
}

export interface TopologySchema {
  version: typeof TOPOLOGY_VERSION;
  nodes: SimNode[];
  edges: SimEdge[];
  viewport: CanvasViewport;
}

// ─────────────────────────────────────────────────────────────────────────────
// SIMULATION RUNTIME STATE
// These types are NOT stored in Supabase — they live only in the browser
// (SimulationStore / Web Worker) during an active simulation session.
// ─────────────────────────────────────────────────────────────────────────────

export interface NodeRuntimeState {
  nodeId: string;
  health: NodeHealth;
  /** 0–100 percentage of capacity currently consumed. */
  utilisationPct: number;
  /** Current requests per second flowing through this node. */
  currentRps: number;
  /** Number of requests waiting to be processed. */
  queueDepth: number;
  /** Rolling error rate 0–1 over the last 5 seconds. */
  errorRate: number;
}

export interface EdgeFlowState {
  edgeId: string;
  /** Number of visible animated particles (capped at 12). */
  particleCount: number;
  /** Actual requests per second on this edge. */
  throughput: number;
  /** Ratio of errored requests on this edge 0–1. */
  errorRatio: number;
  /** True when a NET_PARTITION chaos scenario affects this edge. */
  isPartitioned: boolean;
}

export interface MetricSnapshot {
  timestamp: number;    // Unix ms
  /** Total successful requests per second across the whole system. */
  throughput: number;
  p50LatencyMs: number;
  p95LatencyMs: number;
  p99LatencyMs: number;
  /** System-wide error rate 0–1. */
  errorRate: number;
  /** Cumulative requests processed since simulation start. */
  totalRequests: number;
}

export interface ChaosEvent {
  scenarioId: ChaosScenarioId;
  /** 'activated' | 'escalated' | 'resolved' */
  phase: "activated" | "escalated" | "resolved";
  /** Node IDs affected by this chaos event. */
  affectedNodeIds: string[];
  timestamp: number;
}

/**
 * SimulationFrame — posted from the Web Worker to the main thread every ~100ms.
 * This is the heartbeat of the simulation. useWorkerBridge consumes this and
 * calls SimulationStore.absorbFrame() to update all reactive state.
 */
export interface SimulationFrame {
  tickId: number;
  timestamp: number;
  nodeStates: Record<string, NodeRuntimeState>;
  edgeFlows: Record<string, EdgeFlowState>;
  globalMetrics: MetricSnapshot;
  chaosEvents: ChaosEvent[];
  /** Node IDs currently at > 90% utilisation. */
  bottlenecks: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// CHAOS SCENARIO DEFINITIONS
// ChaosScenarioDef describes a scenario in the catalogue.
// ActiveScenario describes a currently running instance.
// ─────────────────────────────────────────────────────────────────────────────

export interface ChaosScenarioDef {
  id: ChaosScenarioId;
  name: string;
  tag: string;
  description: string;
  /** Node types this scenario can target. Empty = no target needed (e.g. TrafficSpike). */
  validTargetTypes: NodeType[];
  /** Whether the user must select a target node/edge before activating. */
  requiresTarget: boolean;
  /** Whether the user must configure a parameter before activating (e.g. spike multiplier). */
  requiresConfig: boolean;
}

export interface ActiveScenario {
  id: string;                 // nanoid instance ID — multiple instances of same scenario possible
  scenarioId: ChaosScenarioId;
  targetNodeIds: string[];    // empty if scenario doesn't need a target
  config: Record<string, unknown>; // scenario-specific params e.g. { multiplier: 5, durationSeconds: 30 }
  activatedAt: number;        // Unix ms
  /** Undefined = scenario runs until manually resolved. */
  resolvesAt?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// WORKER MESSAGE PROTOCOL
// All messages between main thread and simulation.worker.ts use these types.
// Discriminated on the `type` field.
// ─────────────────────────────────────────────────────────────────────────────

export type WorkerInboundMessage =
  | { type: "START";         topology: TopologySchema; speed: number }
  | { type: "PAUSE" }
  | { type: "RESUME" }
  | { type: "STOP" }
  | { type: "SET_SPEED";     speed: number }
  | { type: "UPDATE_TOPOLOGY"; topology: TopologySchema }
  | { type: "ACTIVATE_CHAOS";  scenario: ActiveScenario }
  | { type: "DEACTIVATE_CHAOS"; instanceId: string };

export type WorkerOutboundMessage =
  | { type: "FRAME";  frame: SimulationFrame }
  | { type: "READY" }
  | { type: "ERROR";  message: string };

// ─────────────────────────────────────────────────────────────────────────────
// PRESET BLUEPRINT
// ─────────────────────────────────────────────────────────────────────────────

export interface PresetBlueprint {
  slug: string;
  name: string;
  description: string;
  category: "fundamentals" | "patterns";
  topology: TopologySchema;
}

// ─────────────────────────────────────────────────────────────────────────────
// API RESPONSE SHAPES (mirrored by backend Pydantic models)
// ─────────────────────────────────────────────────────────────────────────────

export interface DiagramSummary {
  id: string;
  name: string;
  isPublic: boolean;
  createdAt: string;   // ISO 8601
  updatedAt: string;
}

export interface DiagramResponse extends DiagramSummary {
  topology: TopologySchema;
  shareToken: string | null;
  forkCount: number;
}

export interface DiagramListResponse {
  items: DiagramSummary[];
  total: number;
  page: number;
  pageSize: number;
}

export interface ShareResponse {
  shareUrl: string;
  shareToken: string;
  isPublic: true;
}

export interface ForkResponse {
  diagramId: string;
  name: string;
}
