/**
 * topology.ts — SimuFlow Shared Type Contract
 *
 * This file is the single source of truth for all data structures that cross
 * the frontend ↔ backend ↔ Web Worker boundary.
 *
 * Rules:
 *  1. Never import from React, MobX, or any UI library in this file.
 *  2. The backend Pydantic models in app/models/ must mirror every field here.
 *  3. Increment TOPOLOGY_VERSION on any breaking change to NodeDef or EdgeDef.
 *  4. Add new node types to NodeType enum only — never use raw strings elsewhere.
 */

// ─────────────────────────────────────────────────────────────────────────────
// VERSIONING
// ─────────────────────────────────────────────────────────────────────────────

/** Bumped to 2.0 — expanded NodeType enum (11 new simulation types) + structural layer */
export const TOPOLOGY_VERSION = "2.0" as const;

// ─────────────────────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────────────────────

export enum NodeType {
  // ── Original 8 ──────────────────────────────────────────────────────────
  Client            = "client",
  LoadBalancer      = "load_balancer",
  ApiServer         = "api_server",
  Cache             = "cache",
  Database          = "database",
  Queue             = "queue",
  CDN               = "cdn",
  Microservice      = "microservice",

  // ── New simulation nodes ─────────────────────────────────────────────────
  ApiGateway        = "api_gateway",
  Serverless        = "serverless",
  Worker            = "worker",
  PubSub            = "pub_sub",
  Stream            = "stream",
  RateLimiter       = "rate_limiter",
  ObjectStore       = "object_store",
  ExternalService   = "external_service",
  LLMGateway        = "llm_gateway",
  VectorDB          = "vector_db",
  AgentOrchestrator = "agent_orchestrator",
}

/** Structural nodes render as containers/regions on the canvas.
 *  The simulation engine ignores them entirely. */
export enum StructuralNodeType {
  VPC               = "vpc",
  Subnet            = "subnet",
  AvailabilityZone  = "availability_zone",
  Region            = "region",
  SecurityGroup     = "security_group",
  ServiceMesh       = "service_mesh",
  Firewall          = "firewall",
  NATGateway        = "nat_gateway",
  ToolRegistry      = "tool_registry",
  MemoryFabric      = "memory_fabric",
  ShardAnnotation   = "shard_annotation",
  ReplicaAnnotation = "replica_annotation",
  TextLabel         = "text_label",
}

export enum LBStrategy {
  RoundRobin       = "round_robin",
  LeastConnections = "least_connections",
  Random           = "random",
}

export enum RateLimitAlgorithm {
  TokenBucket    = "token_bucket",
  SlidingWindow  = "sliding_window",
  FixedWindow    = "fixed_window",
}

export enum RejectBehavior {
  Drop  = "drop",   // immediate 429 / rejection
  Queue = "queue",  // hold until a slot is available (adds latency)
}

export enum NodeHealth {
  Idle       = "idle",       // simulation not running
  Healthy    = "healthy",    // utilisation < 60%
  Stressed   = "stressed",   // utilisation 60–90%
  Bottleneck = "bottleneck", // utilisation > 90%
  Failed     = "failed",     // failure rate triggered or chaos killed node
}

export enum ChaosScenarioId {
  DbFailover     = "DB_FAILOVER",
  CacheStampede  = "CACHE_STAMPEDE",
  NetPartition   = "NET_PARTITION",
  TrafficSpike   = "TRAFFIC_SPIKE",
  Cascade        = "CASCADE",
  SlowDependency = "SLOW_DEP",
}

export enum SimulationStatus {
  Idle    = "idle",
  Running = "running",
  Paused  = "paused",
  Chaos   = "chaos", // running with at least one active chaos scenario
}

// ─────────────────────────────────────────────────────────────────────────────
// NODE CONFIGS
// Each NodeType has its own config interface.
// NodeConfig is the discriminated union — narrow using the `nodeType` field.
// ─────────────────────────────────────────────────────────────────────────────

// ── Shared base (capacity-based nodes) ──────────────────────────────────────

export interface BaseNodeConfig {
  /** Max requests per second before node saturates. */
  capacity: number;
  /** Processing latency p50 in milliseconds. */
  latencyMs: number;
  /** Probability 0–1 that a given request fails at this node. */
  failureRate: number;
  /** Request timeout in ms. Requests exceeding this emit an error event. */
  timeoutMs: number;
}

// ── Original 8 ───────────────────────────────────────────────────────────────

export interface ClientConfig {
  /** Outbound requests per second generated by this source node. */
  rps: number;
  /** Whether this client generates burst traffic patterns. */
  burst: boolean;
}

export interface LoadBalancerConfig extends BaseNodeConfig {
  strategy: LBStrategy;
  /** Number of replicas of downstream nodes to distribute across. */
  replicas: number;
}

export interface CacheConfig extends BaseNodeConfig {
  /** Cache hit rate 0–1. On miss, request falls through to backing store. */
  hitRate: number;
}

export interface CDNConfig extends BaseNodeConfig {
  /** Edge cache hit rate 0–1. */
  hitRate: number;
}

export interface QueueConfig {
  /** Processing delay added per message in milliseconds. */
  delayMs: number;
  /** Max queue depth before messages are dropped. 0 = unlimited. */
  maxDepth: number;
}

// ── New simulation nodes ──────────────────────────────────────────────────────

export interface ApiGatewayConfig extends BaseNodeConfig {
  /** Max requests per second allowed per client. 0 = unlimited. */
  rateLimit: number;
  /** Extra milliseconds added per request for auth policy evaluation. */
  authOverheadMs: number;
}

export interface ServerlessConfig {
  /** Latency penalty on a cold invocation (instance was idle). */
  coldStartMs: number;
  /** Latency when the instance is already warm. */
  warmLatencyMs: number;
  /** 0–1 probability that any given invocation hits a cold instance. */
  coldStartProbability: number;
  /** Max simultaneous invocations before throttling begins. */
  concurrencyLimit: number;
  /** Probability 0–1 that an invocation fails. */
  failureRate: number;
  /** Max invocation duration in ms before forced kill. */
  timeoutMs: number;
}

export interface WorkerConfig {
  /** Jobs processed per second (pull-based consumption rate). */
  throughput: number;
  /** Average time to process one job in ms. */
  processingMs: number;
  /** Probability 0–1 that a job fails. */
  failureRate: number;
  /** Max retry attempts before a job is dead-lettered. */
  retries: number;
  /** Number of jobs processed in parallel. */
  concurrency: number;
}

export interface PubSubConfig {
  /** Number of downstream consumers that receive each message. */
  subscriberCount: number;
  /** Time in ms to deliver a message to each subscriber. */
  deliveryLatencyMs: number;
  /** Probability 0–1 of delivery failure per subscriber. */
  failureRate: number;
  /** Max messages buffered before back-pressure. 0 = unlimited. */
  maxDepth: number;
}

export interface StreamConfig {
  /** Number of parallel partitions — determines max consumer parallelism. */
  partitions: number;
  /** Max messages per second the stream can sustain. */
  throughput: number;
  /** How long messages are retained in ms (replay window). */
  retentionMs: number;
  /** Number of independent consumer groups reading the stream. */
  consumerGroups: number;
  /** Probability 0–1 of a write failure. */
  failureRate: number;
}

export interface RateLimiterConfig {
  /** Max requests per second allowed through. */
  rateLimit: number;
  /** How many requests above the limit are absorbed before rejection begins. */
  burstSize: number;
  algorithm: RateLimitAlgorithm;
  rejectBehavior: RejectBehavior;
}

export interface ObjectStoreConfig {
  /** Max read throughput in MB/s. */
  readThroughputMbps: number;
  /** Max write throughput in MB/s. */
  writeThroughputMbps: number;
  /** Per-operation latency to first byte in ms. */
  latencyMs: number;
  /** Probability 0–1 of operation failure. */
  failureRate: number;
  /** Objects larger than this (MB) are rejected. 0 = unlimited. */
  maxObjectSizeMb: number;
}

export interface ExternalServiceConfig {
  /** p50 latency for a successful call in ms. */
  latencyMs: number;
  /** p99 latency — the spread between p50 and p99 causes tail latency issues. */
  p99LatencyMs: number;
  /** Probability 0–1 the external call fails. */
  failureRate: number;
  /** Your service's timeout on this dependency in ms. */
  timeoutMs: number;
  /** Max calls per second the provider allows. 0 = unlimited. */
  rateLimit: number;
}

export interface LLMGatewayConfig {
  /** Token generation speed of the model (tokens/s). Drives latency. */
  tokensPerSecond: number;
  /** Average input token count per request. */
  avgPromptTokens: number;
  /** Average output token count per request. */
  avgCompletionTokens: number;
  /** Max tokens per minute allowed by the provider. */
  rateLimitTpm: number;
  /** Probability 0–1 of model error or content rejection. */
  failureRate: number;
  /** Max time to wait for completion in ms before timeout. */
  timeoutMs: number;
}

export interface VectorDBConfig {
  /** Max queries per second before saturation. */
  queryCapacity: number;
  /** Number of vectors in the index (millions) — affects per-query latency. */
  indexSizeM: number;
  /** Vector dimensions — affects compute cost per query. */
  dimensions: number;
  /** p50 latency for an ANN query in ms. */
  queryLatencyMs: number;
  /** Probability 0–1 of query failure. */
  failureRate: number;
}

export interface AgentOrchestratorConfig {
  /** Max number of agent loops that can run simultaneously. */
  maxConcurrentAgents: number;
  /** Latency per orchestration step (routing + state management) in ms. */
  stepLatencyMs: number;
  /** Max steps per agent loop before timeout kill. */
  maxSteps: number;
  /** Probability 0–1 of orchestration failure per step. */
  failureRate: number;
  /** Total time budget for one full agent run in ms. */
  timeoutMs: number;
}

// ── Discriminated union ───────────────────────────────────────────────────────

export type NodeConfig =
  // Original 8
  | { nodeType: NodeType.Client;            config: ClientConfig }
  | { nodeType: NodeType.LoadBalancer;      config: LoadBalancerConfig }
  | { nodeType: NodeType.ApiServer;         config: BaseNodeConfig }
  | { nodeType: NodeType.Cache;             config: CacheConfig }
  | { nodeType: NodeType.Database;          config: BaseNodeConfig }
  | { nodeType: NodeType.Queue;             config: QueueConfig }
  | { nodeType: NodeType.CDN;               config: CDNConfig }
  | { nodeType: NodeType.Microservice;      config: BaseNodeConfig }
  // New 11
  | { nodeType: NodeType.ApiGateway;        config: ApiGatewayConfig }
  | { nodeType: NodeType.Serverless;        config: ServerlessConfig }
  | { nodeType: NodeType.Worker;            config: WorkerConfig }
  | { nodeType: NodeType.PubSub;            config: PubSubConfig }
  | { nodeType: NodeType.Stream;            config: StreamConfig }
  | { nodeType: NodeType.RateLimiter;       config: RateLimiterConfig }
  | { nodeType: NodeType.ObjectStore;       config: ObjectStoreConfig }
  | { nodeType: NodeType.ExternalService;   config: ExternalServiceConfig }
  | { nodeType: NodeType.LLMGateway;        config: LLMGatewayConfig }
  | { nodeType: NodeType.VectorDB;          config: VectorDBConfig }
  | { nodeType: NodeType.AgentOrchestrator; config: AgentOrchestratorConfig };

// ─────────────────────────────────────────────────────────────────────────────
// STRUCTURAL NODES
// Visual containers / regions only. Simulation engine ignores these entirely.
// ─────────────────────────────────────────────────────────────────────────────

export interface StructuralNode {
  id: string;
  label: string;
  structuralType: StructuralNodeType;
  position: CanvasPosition;
  /** Width of the container in canvas units. */
  width: number;
  /** Height of the container in canvas units. */
  height: number;
  /** Optional hex colour tint for the container background. */
  color?: string;
  /** Optional freeform annotation text shown inside the container. */
  notes?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// TOPOLOGY — the diagram data model saved to Supabase and loaded into the canvas
// ─────────────────────────────────────────────────────────────────────────────

export interface CanvasPosition {
  x: number;
  y: number;
}

export interface CanvasViewport {
  x: number;
  y: number;
  zoom: number;
}

/**
 * A single simulation node on the canvas.
 * Narrow using `node.nodeType` before accessing `node.config`.
 */
export type SimNode = {
  id: string;
  label: string;
  position: CanvasPosition;
} & NodeConfig;

export interface SimEdge {
  id: string;
  sourceId: string;
  targetId: string;
  /** Optional label shown on edge at idle — e.g. "SQL queries" */
  label?: string;
}

export interface TopologySchema {
  version: typeof TOPOLOGY_VERSION;
  nodes: SimNode[];
  edges: SimEdge[];
  /** Structural containers — engine ignores these. */
  structuralNodes: StructuralNode[];
  viewport: CanvasViewport;
}

// ─────────────────────────────────────────────────────────────────────────────
// SIMULATION RUNTIME STATE
// ─────────────────────────────────────────────────────────────────────────────

export interface NodeRuntimeState {
  nodeId: string;
  health: NodeHealth;
  /** 0–100 percentage of capacity currently consumed. */
  utilisationPct: number;
  /** Current requests (or jobs) per second flowing through this node. */
  currentRps: number;
  /** Number of requests/jobs waiting to be processed. */
  queueDepth: number;
  /** Rolling error rate 0–1 over the last 5 seconds. */
  errorRate: number;
}

export interface EdgeFlowState {
  edgeId: string;
  /** Number of visible animated particles (capped at 12). */
  particleCount: number;
  /** Actual requests per second on this edge. */
  throughput: number;
  /** Ratio of errored requests on this edge 0–1. */
  errorRatio: number;
  /** True when a NET_PARTITION chaos scenario affects this edge. */
  isPartitioned: boolean;
}

export interface MetricSnapshot {
  timestamp: number;
  throughput: number;
  p50LatencyMs: number;
  p95LatencyMs: number;
  p99LatencyMs: number;
  errorRate: number;
  totalRequests: number;
}

export interface ChaosEvent {
  scenarioId: ChaosScenarioId;
  phase: "activated" | "escalated" | "resolved";
  affectedNodeIds: string[];
  timestamp: number;
}

export interface SimulationFrame {
  tickId: number;
  timestamp: number;
  nodeStates: Record<string, NodeRuntimeState>;
  edgeFlows: Record<string, EdgeFlowState>;
  globalMetrics: MetricSnapshot;
  chaosEvents: ChaosEvent[];
  bottlenecks: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// CHAOS
// ─────────────────────────────────────────────────────────────────────────────

export interface ChaosScenarioDef {
  id: ChaosScenarioId;
  name: string;
  tag: string;
  description: string;
  validTargetTypes: NodeType[];
  requiresTarget: boolean;
  requiresConfig: boolean;
}

export interface ActiveScenario {
  id: string;
  scenarioId: ChaosScenarioId;
  targetNodeIds: string[];
  config: Record<string, unknown>;
  activatedAt: number;
  resolvesAt?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// WORKER MESSAGE PROTOCOL
// ─────────────────────────────────────────────────────────────────────────────

export type WorkerInboundMessage =
  | { type: "START";            topology: TopologySchema; speed: number }
  | { type: "PAUSE" }
  | { type: "RESUME" }
  | { type: "STOP" }
  | { type: "SET_SPEED";        speed: number }
  | { type: "UPDATE_TOPOLOGY";  topology: TopologySchema }
  | { type: "ACTIVATE_CHAOS";   scenario: ActiveScenario }
  | { type: "DEACTIVATE_CHAOS"; instanceId: string };

export type WorkerOutboundMessage =
  | { type: "FRAME"; frame: SimulationFrame }
  | { type: "READY" }
  | { type: "ERROR"; message: string };

// ─────────────────────────────────────────────────────────────────────────────
// PRESET BLUEPRINT
// ─────────────────────────────────────────────────────────────────────────────

export interface PresetBlueprint {
  slug: string;
  name: string;
  description: string;
  category: "fundamentals" | "patterns" | "ai";
  topology: TopologySchema;
}

// ─────────────────────────────────────────────────────────────────────────────
// API RESPONSE SHAPES
// ─────────────────────────────────────────────────────────────────────────────

export interface DiagramSummary {
  id: string;
  name: string;
  isPublic: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface DiagramResponse extends DiagramSummary {
  topology: TopologySchema;
  shareToken: string | null;
  forkCount: number;
}

export interface DiagramListResponse {
  items: DiagramSummary[];
  total: number;
  page: number;
  pageSize: number;
}

export interface ShareResponse {
  shareUrl: string;
  shareToken: string;
  isPublic: true;
}

export interface ForkResponse {
  diagramId: string;
  name: string;
}
